import Head from "next/head";
import OrderList from "@/components/OrderList";
import { CreateOrderBtn, HomeContainer, OverviewCard, OverviewContainer, OverviewTrendTag } from "@/styles/Home.style";

import Layout from "@/components/Layout";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Simple Procurement App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <>
          <HomeContainer>
            <CreateOrderBtn
              onClick={() => {
                router.push("/order/new");
              }}
            >
              + Create Order
            </CreateOrderBtn>

            {/* <OverviewContainer>
              <OverviewCard>
                <div>
                  <div className="overview-text-area">
                    <h2>Total Orders</h2>
                    <p>20</p>
                  </div>
    
                  <OverviewTrendTag>20%</OverviewTrendTag>
                </div>
              </OverviewCard>
            </OverviewContainer> */}

            <OrderList />
          </HomeContainer>
        </>
      </Layout>
    </>
  );
}
